name: Notify Discord

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, closed]

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
    - name: Send notification to Discord
      env:
        DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
      run: |
        if [ "${{ github.event_name }}" = "push" ]; then
          REPO="${{ github.repository }}"
          BRANCH=$(echo "${{ github.ref }}" | sed 's/refs\/heads\///')
          AUTHOR="${{ github.actor }}"
          COMMIT_COUNT=$(echo "${{ github.event.commits }}" | jq '. | length')
          COMMIT_URL="${{ github.event.compare }}"
          COMMITS=$(echo "${{ github.event.commits }}" | jq -r '.[] | "Commit: \(.message) by \(.author.name) [View Commit](\(.url))"')

          MESSAGE=$(cat <<EOF
**Repository:** $REPO
**Branch:** $BRANCH
**Commits:** $COMMIT_COUNT
**Author:** $AUTHOR

$COMMITS
[Compare Changes]($COMMIT_URL)
EOF
          )
        elif [ "${{ github.event_name }}" = "pull_request" ]; then
          REPO="${{ github.repository }}"
          PR_TITLE="${{ github.event.pull_request.title }}"
          PR_URL="${{ github.event.pull_request.html_url }}"
          ACTION="${{ github.event.action }}"
          AUTHOR="${{ github.actor }}"

          MESSAGE=$(cat <<EOF
**Repository:** $REPO
**Pull Request:** [$PR_TITLE]($PR_URL)
**Action:** $ACTION
**Author:** $AUTHOR
EOF
          )
        fi

        curl -H "Content-Type: application/json" \
             -d "{\"content\": \"$MESSAGE\"}" \
             $DISCORD_WEBHOOK_URL

