name: Notify Discord

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, closed]

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
    - name: Send notification to Discord
      env:
        DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
      run: |
        if [ "${{ github.event_name }}" = "push" ]; then
          MESSAGE="New push to ${{ github.repository }} by ${{ github.actor }}: ${{ github.head_ref || github.ref_name }} - ${{ github.event.head_commit.message }}"
        elif [ "${{ github.event_name }}" = "pull_request" ]; then
          if [ "${{ github.event.action }}" = "opened" ]; then
            MESSAGE="New pull request in ${{ github.repository }}: ${{ github.event.pull_request.title }} by ${{ github.actor }}"
          elif [ "${{ github.event.action }}" = "closed" ]; then
            MESSAGE="Pull request closed in ${{ github.repository }}: ${{ github.event.pull_request.title }} by ${{ github.actor }}"
          fi
        fi

        curl -H "Content-Type: application/json" \
             -d "{\"content\": \"$MESSAGE\"}" \
             $DISCORD_WEBHOOK_URL

