name: Discord Updates

on:
  workflow_call:

jobs:
  discord-notification:
    runs-on: ubuntu-latest
    steps:
      - name: Send Discord Notification
        uses: Ilshidur/action-discord@master
        with:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          args: 'Repository: ${{ github.repository }} - Event: ${{ github.event_name }} - Commit: ${{ github.sha }}'

