name: Discord Updates

on:
  workflow_call:
    inputs:
      discord_webhook_url:
        required: true
        type: string

jobs:
  discord-notification:
    runs-on: ubuntu-latest
    steps:
      - name: Send Discord Notification
        env:
          DISCORD_WEBHOOK: ${{ inputs.discord_webhook_url }}
        uses: Ilshidur/action-discord@master
        with:
          args: 'Repository: ${{ github.repository }} - Event: ${{ github.event_name }} - Commit: ${{ github.sha }}'

