name: Notify Discord
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, closed]
jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
    - name: Send notification to Discord
      env:
        DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}
        DISCORD_CHANNEL_ID: ${{ secrets.DISCORD_CHANNEL_ID }}
      run: |
        if [ "${{ github.event_name }}" = "push" ]; then
          REPO="${{ github.repository }}"
          BRANCH=$(echo "${{ github.ref }}" | sed 's/refs\/heads\///')
          AUTHOR="${{ github.actor }}"
          COMMIT_URL="${{ github.event.compare }}"
          MESSAGE="**Repository:** $REPO\n**Branch:** $BRANCH\n**Author:** $AUTHOR\n[Compare Changes]($COMMIT_URL)"
        elif [ "${{ github.event_name }}" = "pull_request" ]; then
          REPO="${{ github.repository }}"
          PR_TITLE="${{ github.event.pull_request.title }}"
          PR_URL="${{ github.event.pull_request.html_url }}"
          ACTION="${{ github.event.action }}"
          AUTHOR="${{ github.actor }}"
          MESSAGE="**Repository:** $REPO\n**Pull Request:** [$PR_TITLE]($PR_URL)\n**Action:** $ACTION\n**Author:** $AUTHOR"
        fi
        curl -H "Authorization: Bot $DISCORD_BOT_TOKEN" \
             -H "Content-Type: application/json" \
             -X POST \
             -d "{\"content\":\"$MESSAGE\"}" \
             https://discordapp.com/api/channels/$DISCORD_CHANNEL_ID/messages
