name: Main Workflow

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run Main Job
        run: echo "Running main job..."
      - name: Send Discord Dev Logs
        uses: ./.github/workflows/discord-devlogs.yml

