name: Main Workflow

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  discord-updates:
    uses: ./.github/workflows/discord-updates.yml
    with:
      discord_webhook_url: ${{ secrets.DISCORD_WEBHOOK_URL }}

